var dataReg = [
{
   "adr": 0,
   "name": "versionController",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 1,
   "name": "versionFirmware",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 2,
   "name": "serialNumber",
   "value": [0, 0, 0, 0, 0, 0],
   "default": [0, 0, 0, 0, 0, 0],
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 6,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 3,
   "name": "displayBrightnesLevel",
   "value": 50,
   "default": 50,
   "scale": 0,
   "min": 0,
   "max": 100,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 4,
   "name": "displayContarstLevel",
   "value": 30,
   "default": 30,
   "scale": 0,
   "min": 0,
   "max": 100,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 5,
   "name": "displaySleepDelay",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 2,
   "max": 600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 6,
   "name": "hysteresisLevel",
   "value": 20,
   "default": 20,
   "scale": -1,
   "min": 0,
   "max": 1000,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 7,
   "name": "moduleSetup",
   "value": 3,
   "default": 3,
   "scale": 0,
   "min": 0,
   "max": 3,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "moduleType",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "alarmAllBlock",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },
   ]
},{
   "adr": 8,
   "name": "oilPressureSetup",
   "value": 51,
   "default": 51,
   "scale": 0,
   "min": 0,
   "max": 63,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 5,
   "bit": [
       {
           "name": "oilPressureSensorType",
           "mask": 15,
           "max": 11,
           "min": 0,
           "shift": 0,
       },{
           "name": "oilPressureOpenCircuitAlarmEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "oilPressureAlarmEnb",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "oilPressurePreAlarmEnb",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "oilPressureUnitsEnb",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },
   ]
},{
   "adr": 9,
   "name": "oilPressureAlarmLevel",
   "value": 103,
   "default": 103,
   "scale": -2,
   "min": 0,
   "max": 1030,
   "units": "Бар",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 10,
   "name": "oilPressurePreAlarmLevel",
   "value": 124,
   "default": 124,
   "scale": -2,
   "min": 0,
   "max": 1030,
   "units": "Бар",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 11,
   "name": "coolantTempSetup",
   "value": 51,
   "default": 51,
   "scale": 0,
   "min": 0,
   "max": 63,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 6,
   "bit": [
       {
           "name": "coolantTempSensorType",
           "mask": 15,
           "max": 11,
           "min": 0,
           "shift": 0,
       },{
           "name": "coolantTempOpenCircuitAlarmEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "coolantHightTempAlarmEnb",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "coolantHightTempPreAlarmEnb",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "coolantTempHeaterEnb",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "coolantTempCoolerEnb",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 12,
   "name": "coolantHightTempAlarmLevel",
   "value": 96,
   "default": 96,
   "scale": 0,
   "min": 0,
   "max": 250,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 13,
   "name": "coolantHightTempPreAlarmLevel",
   "value": 90,
   "default": 90,
   "scale": 0,
   "min": 0,
   "max": 250,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 14,
   "name": "coolantTempHeaterOffLevel",
   "value": 60,
   "default": 60,
   "scale": 0,
   "min": 0,
   "max": 250,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 15,
   "name": "coolantTempHeaterOnLevel",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 0,
   "max": 250,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 16,
   "name": "coolantTempCoolerOffLevel",
   "value": 80,
   "default": 80,
   "scale": 0,
   "min": 0,
   "max": 250,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 17,
   "name": "coolantTempCoolerOnLevel",
   "value": 120,
   "default": 120,
   "scale": 0,
   "min": 0,
   "max": 250,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 18,
   "name": "fuelLevelSetup",
   "value": 411,
   "default": 411,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 7,
   "bit": [
       {
           "name": "fuelLevelSensorType",
           "mask": 7,
           "max": 5,
           "min": 0,
           "shift": 0,
       },{
           "name": "fuelLevelOpenCircuitAlarmEnb",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "fuelLevelLowAlarmEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "fuelLevelLowPreAlarmEnb",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "fuelLevelHightPreAlarmEnb",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "fuelLevelHightAlarmEnb",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "fuelPumpEnb",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 19,
   "name": "fuelLevelLowAlarmLevel",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 0,
   "max": 95,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 20,
   "name": "fuelLevelLowAlarmDelay",
   "value": 100,
   "default": 100,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 21,
   "name": "fuelLevelLowPreAlarmLevel",
   "value": 25,
   "default": 25,
   "scale": 0,
   "min": 1,
   "max": 96,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 22,
   "name": "fuelLevelLowPreAlarmDelay",
   "value": 100,
   "default": 100,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 23,
   "name": "fuelLevelHightPreAlarmLevel",
   "value": 65,
   "default": 65,
   "scale": 0,
   "min": 3,
   "max": 98,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 24,
   "name": "fuelLevelHightPreAlarmDelay",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 25,
   "name": "fuelLevelHightAlarmLevel",
   "value": 90,
   "default": 90,
   "scale": 0,
   "min": 5,
   "max": 100,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 26,
   "name": "fuelLevelHightAlarmDelay",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 27,
   "name": "fuelPumpOnLevel",
   "value": 30,
   "default": 30,
   "scale": 0,
   "min": 0,
   "max": 100,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 28,
   "name": "fuelPumpOffLevel",
   "value": 70,
   "default": 70,
   "scale": 0,
   "min": 0,
   "max": 100,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 29,
   "name": "speedSetup",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "speedEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "speedLowAlarmEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },
   ]
},{
   "adr": 30,
   "name": "speedToothNumber",
   "value": 190,
   "default": 190,
   "scale": 0,
   "min": 10,
   "max": 500,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 31,
   "name": "speedLowAlarmLevel",
   "value": 1200,
   "default": 1200,
   "scale": 0,
   "min": 0,
   "max": 6000,
   "units": "RPM",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 32,
   "name": "speedHightAlarmLevel",
   "value": 1710,
   "default": 1710,
   "scale": 0,
   "min": 0,
   "max": 6000,
   "units": "RPM",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 33,
   "name": "diaSetup",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "diaFunction",
           "mask": 31,
           "max": 27,
           "min": 0,
           "shift": 0,
       },{
           "name": "diaPolarity",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "diaAction",
           "mask": 192,
           "max": 3,
           "min": 0,
           "shift": 6,
       },{
           "name": "diaArming",
           "mask": 768,
           "max": 4,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 34,
   "name": "diaDelay",
   "value": 15,
   "default": 15,
   "scale": 0,
   "min": 0,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 35,
   "name": "diaMessage",
   "value": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "default": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "S",
   "rw": "rw",
   "len": 16,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 36,
   "name": "dibSetup",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "dibFunction",
           "mask": 31,
           "max": 27,
           "min": 0,
           "shift": 0,
       },{
           "name": "dibPolarity",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "dibAction",
           "mask": 192,
           "max": 3,
           "min": 0,
           "shift": 6,
       },{
           "name": "dibArming",
           "mask": 768,
           "max": 4,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 37,
   "name": "dibDelay",
   "value": 15,
   "default": 15,
   "scale": 0,
   "min": 0,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 38,
   "name": "dibMessage",
   "value": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "default": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "S",
   "rw": "rw",
   "len": 16,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 39,
   "name": "dicSetup",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "dicFunction",
           "mask": 31,
           "max": 27,
           "min": 0,
           "shift": 0,
       },{
           "name": "dicPolarity",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "dicAction",
           "mask": 192,
           "max": 3,
           "min": 0,
           "shift": 6,
       },{
           "name": "dicArming",
           "mask": 768,
           "max": 4,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 40,
   "name": "dicDelay",
   "value": 15,
   "default": 15,
   "scale": 0,
   "min": 0,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 41,
   "name": "dicMessage",
   "value": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "default": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "S",
   "rw": "rw",
   "len": 16,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 42,
   "name": "didSetup",
   "value": 64,
   "default": 64,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "didFunction",
           "mask": 31,
           "max": 27,
           "min": 0,
           "shift": 0,
       },{
           "name": "didPolarity",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "didAction",
           "mask": 192,
           "max": 3,
           "min": 0,
           "shift": 6,
       },{
           "name": "didArming",
           "mask": 768,
           "max": 4,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 43,
   "name": "didDelay",
   "value": 15,
   "default": 15,
   "scale": 0,
   "min": 0,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 44,
   "name": "didMessage",
   "value": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "default": [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "S",
   "rw": "rw",
   "len": 16,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 45,
   "name": "doSetup",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 6,
   "bit": [
       {
           "name": "doaNOC",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "dobNOC",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "docNOC",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "dodNOC",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "doeNOC",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "dofNOC",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },
   ]
},{
   "adr": 46,
   "name": "doabType",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "doaType",
           "mask": 255,
           "max": 255,
           "min": 0,
           "shift": 0,
       },{
           "name": "dobType",
           "mask": 65280,
           "max": 255,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 47,
   "name": "docdType",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "docType",
           "mask": 255,
           "max": 255,
           "min": 0,
           "shift": 0,
       },{
           "name": "dodType",
           "mask": 65280,
           "max": 255,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 48,
   "name": "doefType",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1023,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "doeType",
           "mask": 255,
           "max": 255,
           "min": 0,
           "shift": 0,
       },{
           "name": "dofType",
           "mask": 65280,
           "max": 255,
           "min": 0,
           "shift": 8,
       },
   ]
},{
   "adr": 49,
   "name": "timerMainsTransientDelay",
   "value": 1,
   "default": 1,
   "scale": -1,
   "min": 1,
   "max": 100,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 50,
   "name": "timerStartDelay",
   "value": 5,
   "default": 5,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 51,
   "name": "timerCranking",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 1,
   "max": 30,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 52,
   "name": "timerCrankDelay",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 1,
   "max": 30,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 53,
   "name": "timerStartupIdleTime",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 54,
   "name": "timerNominalRPMDelay",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 1,
   "max": 30,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 55,
   "name": "timerSafetyOnDelay",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 1,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 56,
   "name": "timerWarming",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 57,
   "name": "timerTransferDelay",
   "value": 6,
   "default": 6,
   "scale": -1,
   "min": 1,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 58,
   "name": "timerGenBreakerTripPulse",
   "value": 5,
   "default": 5,
   "scale": -1,
   "min": 1,
   "max": 50,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 59,
   "name": "timerGenBreakerClosePulse",
   "value": 5,
   "default": 5,
   "scale": -1,
   "min": 1,
   "max": 50,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 60,
   "name": "timerMainsBreakerTripPulse",
   "value": 5,
   "default": 5,
   "scale": -1,
   "min": 1,
   "max": 50,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 61,
   "name": "timerMainsBreakerClosePulse",
   "value": 5,
   "default": 5,
   "scale": -1,
   "min": 1,
   "max": 50,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 62,
   "name": "timerReturnDelay",
   "value": 30,
   "default": 30,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 63,
   "name": "timerCooling",
   "value": 60,
   "default": 60,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 64,
   "name": "timerCoolingIdle",
   "value": 20,
   "default": 20,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 65,
   "name": "timerSolenoidHold",
   "value": 20,
   "default": 20,
   "scale": 0,
   "min": 0,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 66,
   "name": "timerFailStopDelay",
   "value": 30,
   "default": 30,
   "scale": 0,
   "min": 1,
   "max": 60,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 67,
   "name": "timerGenTransientDelay",
   "value": 10,
   "default": 10,
   "scale": -1,
   "min": 1,
   "max": 100,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 68,
   "name": "genSetup",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 0,
   "max": 255,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "genPowerGeneratorControlEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "genAcSys",
           "mask": 6,
           "max": 3,
           "min": 0,
           "shift": 1,
       },
   ]
},{
   "adr": 69,
   "name": "genRatedActivePowerLevel",
   "value": 40000,
   "default": 40000,
   "scale": 0,
   "min": 0,
   "max": 10000,
   "units": "кВт",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 70,
   "name": "genRatedReactivePowerLevel",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 10000,
   "units": "кВАР",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 71,
   "name": "genRatedApparentPowerLevel",
   "value": 200,
   "default": 200,
   "scale": 0,
   "min": 0,
   "max": 10000,
   "units": "кВА",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 72,
   "name": "genRatedFrequencyLevel",
   "value": 500,
   "default": 500,
   "scale": -1,
   "min": 2,
   "max": 747,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 73,
   "name": "genCurrentPrimaryLevel",
   "value": 600,
   "default": 600,
   "scale": 0,
   "min": 5,
   "max": 8000,
   "units": "А",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 74,
   "name": "genCurrentFullLoadRatingLevel",
   "value": 500,
   "default": 500,
   "scale": 0,
   "min": 5,
   "max": 8000,
   "units": "А",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 75,
   "name": "genCurrentTrasformRatioLevel",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 1,
   "max": 100,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 76,
   "name": "genAlarms",
   "value": 7167,
   "default": 7167,
   "scale": 0,
   "min": 0,
   "max": 65535,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 12,
   "bit": [
       {
           "name": "genUnderVoltageAlarmEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "genUnderVoltagePreAlarmEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "genOverVoltagePreAlarmEnb",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "genUnderFrequencyAlarmEnb",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "genUnderFrequencyPreAlarmEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "genOverFrequencyPreAlarmEnb",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "genOverFrequencyAlarmEnb",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "genCurrentOverloadProtectionEnb",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "genCurrentOverPhaseImbalanceEnb",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "genCurrentOverAlarmAction",
           "mask": 1536,
           "max": 3,
           "min": 0,
           "shift": 9,
       },{
           "name": "genCurrentOverloadProtectionAction",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },{
           "name": "genCurrentOverPhaseImbalanceAction",
           "mask": 4096,
           "max": 1,
           "min": 0,
           "shift": 12,
       },
   ]
},{
   "adr": 77,
   "name": "genUnderVoltageAlarmLevel",
   "value": 318,
   "default": 318,
   "scale": 0,
   "min": 86,
   "max": 708,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 78,
   "name": "genUnderVoltagePreAlarmLevel",
   "value": 339,
   "default": 339,
   "scale": 0,
   "min": 88,
   "max": 710,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 79,
   "name": "genOverVoltagePreAlarmLevel",
   "value": 439,
   "default": 439,
   "scale": 0,
   "min": 93,
   "max": 715,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 80,
   "name": "genOverVoltageAlarmLevel",
   "value": 458,
   "default": 458,
   "scale": 0,
   "min": 95,
   "max": 717,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 81,
   "name": "genUnderFrequencyAlarmLevel",
   "value": 400,
   "default": 400,
   "scale": -1,
   "min": 0,
   "max": 744,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 82,
   "name": "genUnderFrequencyPreAlarmLevel",
   "value": 420,
   "default": 420,
   "scale": -1,
   "min": 1,
   "max": 745,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 83,
   "name": "genOverFrequencyPreAlarmLevel",
   "value": 540,
   "default": 540,
   "scale": -1,
   "min": 4,
   "max": 747,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 84,
   "name": "genOverFrequencyAlarmLevel",
   "value": 550,
   "default": 550,
   "scale": -1,
   "min": 5,
   "max": 749,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 85,
   "name": "genOverCurrentThermalProtectionLevel",
   "value": 20,
   "default": 20,
   "scale": 0,
   "min": 90,
   "max": 200,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 86,
   "name": "genOverCurrentCutoffLevel",
   "value": 40,
   "default": 40,
   "scale": 0,
   "min": 200,
   "max": 500,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 87,
   "name": "genOverCurrentAlarmLevel",
   "value": 100,
   "default": 100,
   "scale": 0,
   "min": 50,
   "max": 120,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 88,
   "name": "genOverCurrentAlarmDelay",
   "value": 60,
   "default": 60,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 89,
   "name": "genCurrentOverloadProtectionLevel",
   "value": 100,
   "default": 100,
   "scale": 0,
   "min": 1,
   "max": 125,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 90,
   "name": "genCurrentOverloadProtectionDelay",
   "value": 5,
   "default": 5,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 91,
   "name": "genCurrentOverPhaseImbalanceLevel",
   "value": 100,
   "default": 100,
   "scale": 0,
   "min": 1,
   "max": 125,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 92,
   "name": "genCurrentOverPhaseImbalanceDelay",
   "value": 60,
   "default": 60,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 93,
   "name": "mainsSetup",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 0,
   "max": 31,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "mainsControlEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "mainsPowerOffImmediatelyEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },
   ]
},{
   "adr": 94,
   "name": "mainsAlarms",
   "value": 15,
   "default": 15,
   "scale": 0,
   "min": 0,
   "max": 15,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "mainsUnderVoltageAlarmEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "mainsOverVoltageAlarmEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "mainsUnderFrequencyAlarmEnb",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "mainsOverFrequencyAlarmEnb",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },
   ]
},{
   "adr": 95,
   "name": "mainsUnderVoltageAlarmLevel",
   "value": 318,
   "default": 318,
   "scale": 0,
   "min": 86,
   "max": 713,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 96,
   "name": "mainsOverVoltageAlarmLevel",
   "value": 438,
   "default": 438,
   "scale": 0,
   "min": 90,
   "max": 717,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 97,
   "name": "mainsUnderFrequencyAlarmLevel",
   "value": 450,
   "default": 450,
   "scale": -1,
   "min": 0,
   "max": 747,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 98,
   "name": "mainsOverFrequencyAlarmLevel",
   "value": 520,
   "default": 520,
   "scale": -1,
   "min": 2,
   "max": 749,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 99,
   "name": "engineSetup",
   "value": 3,
   "default": 3,
   "scale": 0,
   "min": 0,
   "max": 63,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "engineStartAttempts",
           "mask": 15,
           "max": 9,
           "min": 1,
           "shift": 0,
       },{
           "name": "enginePreHeatEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },
   ]
},{
   "adr": 100,
   "name": "enginePreHeatLevel",
   "value": 50,
   "default": 50,
   "scale": 0,
   "min": 0,
   "max": 100,
   "units": "C",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 101,
   "name": "enginePreHeatDelay",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 102,
   "name": "starterStopSetup",
   "value": 5,
   "default": 5,
   "scale": 0,
   "min": 0,
   "max": 7,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "starterOilPressureCheckOnStartEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "starterStopOilPressureEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "starterStopChargeAlternatorEnb",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "starterStopSpeedEnb",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },
   ]
},{
   "adr": 103,
   "name": "starterStopGenFreqLevel",
   "value": 210,
   "default": 210,
   "scale": -1,
   "min": 0,
   "max": 400,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 104,
   "name": "starterStopOilPressureLevel",
   "value": 20,
   "default": 20,
   "scale": -1,
   "min": 5,
   "max": 40,
   "units": "Бар",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 105,
   "name": "starterStopChargeAlternatorLevel",
   "value": 60,
   "default": 60,
   "scale": -1,
   "min": 0,
   "max": 400,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 106,
   "name": "starterStopSpeedLevel",
   "value": 15000,
   "default": 15000,
   "scale": -1,
   "min": 0,
   "max": 60000,
   "units": "RPM",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 107,
   "name": "batteryAlarms",
   "value": 15,
   "default": 15,
   "scale": 0,
   "min": 0,
   "max": 15,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 4,
   "bit": [
       {
           "name": "batteryUnderVoltageEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "batteryOverVoltageEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "batteryChargeShutdownEnb",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "batteryChargeWarningEnb",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },
   ]
},{
   "adr": 108,
   "name": "batteryUnderVoltageLevel",
   "value": 100,
   "default": 100,
   "scale": -1,
   "min": 0,
   "max": 397,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 109,
   "name": "batteryUnderVoltageDelay",
   "value": 60,
   "default": 60,
   "scale": 0,
   "min": 0,
   "max": 86400,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 110,
   "name": "batteryOverVoltageLevel",
   "value": 300,
   "default": 300,
   "scale": -1,
   "min": 2,
   "max": 400,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 111,
   "name": "batteryOverVoltageDelay",
   "value": 60,
   "default": 60,
   "scale": 0,
   "min": 0,
   "max": 86400,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 112,
   "name": "batteryChargeShutdownLevel",
   "value": 40,
   "default": 40,
   "scale": -1,
   "min": 0,
   "max": 388,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 113,
   "name": "batteryChargeShutdownDelay",
   "value": 5,
   "default": 5,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 114,
   "name": "batteryChargeWarningLevel",
   "value": 60,
   "default": 60,
   "scale": -1,
   "min": 1,
   "max": 390,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 115,
   "name": "batteryChargeWarningDelay",
   "value": 5,
   "default": 5,
   "scale": 0,
   "min": 0,
   "max": 3600,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 116,
   "name": "maintenanceAlarms",
   "value": 42,
   "default": 42,
   "scale": 0,
   "min": 0,
   "max": 63,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 6,
   "bit": [
       {
           "name": "maintenanceAlarmOilEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "maintenanceAlarmOilAction",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "maintenanceAlarmAirEnb",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "maintenanceAlarmAirAction",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "maintenanceAlarmFuelEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "maintenanceAlarmFuelAction",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },
   ]
},{
   "adr": 117,
   "name": "maintenanceAlarmOilTime",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 10,
   "max": 5000,
   "units": "час",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 118,
   "name": "maintenanceAlarmAirTime",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 10,
   "max": 5000,
   "units": "час",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 119,
   "name": "maintenanceAlarmFuelTime",
   "value": 10,
   "default": 10,
   "scale": 0,
   "min": 10,
   "max": 5000,
   "units": "час",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 120,
   "name": "logSetup",
   "value": 3,
   "default": 3,
   "scale": 0,
   "min": 0,
   "max": 65535,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 2,
   "bit": [
       {
           "name": "logSaveWarningEventsEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "logPositiveEventsEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },
   ]
},{
   "adr": 121,
   "name": "recordSetup",
   "value": 1,
   "default": 1,
   "scale": 0,
   "min": 0,
   "max": 65535,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 16,
   "bit": [
       {
           "name": "recordEnb",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "recordTimeEnb",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "recordDateEnb",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "recordOilPressureEnb",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "recordCoolantTempEnb",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "recordFuelLevelEnb",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "recordSpeedEnb",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "recordInputAEnb",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "recordInputBEnb",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "recordInputCEnb",
           "mask": 512,
           "max": 1,
           "min": 0,
           "shift": 9,
       },{
           "name": "recordInputDEnb",
           "mask": 1024,
           "max": 1,
           "min": 0,
           "shift": 10,
       },{
           "name": "recordVoltageGenEnb",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },{
           "name": "recordFreqGenEnb",
           "mask": 4096,
           "max": 1,
           "min": 0,
           "shift": 12,
       },{
           "name": "recordVoltageNetEnb",
           "mask": 8192,
           "max": 1,
           "min": 0,
           "shift": 13,
       },{
           "name": "recordFreqNetEnb",
           "mask": 16384,
           "max": 1,
           "min": 0,
           "shift": 14,
       },{
           "name": "recordVoltageAccEnb",
           "mask": 32768,
           "max": 1,
           "min": 0,
           "shift": 15,
       },
   ]
},{
   "adr": 122,
   "name": "recordInterval",
   "value": 1000,
   "default": 1000,
   "scale": -1,
   "min": 1,
   "max": 36000,
   "units": "сек",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},];
module.exports.dataReg = dataReg;