var outputReg = [
{
   "adr": 0,
   "name": "oilPressure",
   "value": 0,
   "default": 0,
   "scale": -2,
   "min": 0,
   "max": 1000,
   "units": "Бар",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 1,
   "name": "coolantTemp",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 300,
   "units": "С",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 2,
   "name": "fuelLevel",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 100,
   "units": "%",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 3,
   "name": "speedLevel",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 6000,
   "units": "RPM",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 4,
   "name": "mainsPhaseVoltageL1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 5,
   "name": "mainsPhaseVoltageL2",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 6,
   "name": "mainsPhaseVoltageL3",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 7,
   "name": "mainsLineVoltageL1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 8,
   "name": "mainsLineVoltageL2",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 9,
   "name": "mainsLineVoltageL3",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 10,
   "name": "mainsFreq",
   "value": 0,
   "default": 0,
   "scale": -1,
   "min": 0,
   "max": 750,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 11,
   "name": "generatorPhaseVoltageL1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 12,
   "name": "generatorPhaseVoltageL2",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 13,
   "name": "generatorPhaseVoltageL3",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 14,
   "name": "generatorLineVoltageL1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 15,
   "name": "generatorLineVoltageL2",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 16,
   "name": "generatorLineVoltageL3",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 800,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 17,
   "name": "generatorCurrentL1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1500,
   "units": "А",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 18,
   "name": "generatorCurrentL2",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1500,
   "units": "А",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 19,
   "name": "generatorCurrentL3",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1500,
   "units": "А",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 20,
   "name": "generatorFreq",
   "value": 0,
   "default": 0,
   "scale": -1,
   "min": 0,
   "max": 750,
   "units": "Гц",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 21,
   "name": "generatorCosFi",
   "value": 0,
   "default": 0,
   "scale": -2,
   "min": 0,
   "max": 100,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 22,
   "name": "generatorPowerActive",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1000,
   "units": "кВт",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 23,
   "name": "generatorPowerReactive",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1000,
   "units": "кВАР",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 24,
   "name": "generatorPowerFull",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 1000,
   "units": "кВА",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 25,
   "name": "batteryVoltage",
   "value": 0,
   "default": 0,
   "scale": -1,
   "min": 0,
   "max": 400,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 26,
   "name": "chargerVoltage",
   "value": 0,
   "default": 0,
   "scale": -1,
   "min": 0,
   "max": 400,
   "units": "В",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 27,
   "name": "externalDevices",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 5,
   "bit": [
       {
           "name": "externalCharger",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "externalCoolantHeater",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "externalCoolantCooler",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "externalFuelPump",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "externalPreHeater",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },
   ]
},{
   "adr": 28,
   "name": "digitalOutput",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 12,
   "bit": [
       {
           "name": "digitalOutputA",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "digitalOutputB",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "digitalOutputC",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "digitalOutputD",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "digitalOutputE",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "digitalOutputF",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "digitalOutputG",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "digitalOutputH",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "digitalOutputI",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "digitalOutputJ",
           "mask": 512,
           "max": 1,
           "min": 0,
           "shift": 9,
       },{
           "name": "digitalOutputK",
           "mask": 1024,
           "max": 1,
           "min": 0,
           "shift": 10,
       },{
           "name": "digitalOutputL",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },
   ]
},{
   "adr": 29,
   "name": "digitalInput",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 12,
   "bit": [
       {
           "name": "digitalInputA",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "digitalInputB",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "digitalInputC",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "digitalInputD",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "digitalInputE",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "digitalInputF",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "digitalInputG",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "digitalInputH",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "digitalInputI",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "digitalInputJ",
           "mask": 512,
           "max": 1,
           "min": 0,
           "shift": 9,
       },{
           "name": "digitalInputK",
           "mask": 1024,
           "max": 1,
           "min": 0,
           "shift": 10,
       },{
           "name": "digitalInputL",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },
   ]
},{
   "adr": 30,
   "name": "deviceStatus",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 31,
   "name": "status",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 6,
   "bit": [
       {
           "name": "statusAlarm",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "statusWarning",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "statusMainsFail",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "statusDPSready",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "statusReadyToStart",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "statusGeneratorRedy",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },
   ]
},{
   "adr": 32,
   "name": "logLen",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 33,
   "name": "logAdr",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 34,
   "name": "logRecordData0",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 35,
   "name": "logRecordData1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 36,
   "name": "logRecordEvent",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 0,
   "bit": []
},{
   "adr": 37,
   "name": "error0",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 16,
   "bit": [
       {
           "name": "errorExternEmegencyStop",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "errorStartFail",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "errorStopFail",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "errorOilLowPressure",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "errorOilSensor",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "errorTempHight",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "errorTempSensor",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "errorFuelLowLevel",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "errorFuelHightLevel",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "errorFuelSensor",
           "mask": 512,
           "max": 1,
           "min": 0,
           "shift": 9,
       },{
           "name": "errorSpeedHight",
           "mask": 1024,
           "max": 1,
           "min": 0,
           "shift": 10,
       },{
           "name": "errorSpeedLow",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },{
           "name": "errorSpeedSensor",
           "mask": 4096,
           "max": 1,
           "min": 0,
           "shift": 12,
       },{
           "name": "errorGenLowVoltage",
           "mask": 8192,
           "max": 1,
           "min": 0,
           "shift": 13,
       },{
           "name": "errorGenHightVoltage",
           "mask": 16384,
           "max": 1,
           "min": 0,
           "shift": 14,
       },{
           "name": "errorGenLowFreq",
           "mask": 32768,
           "max": 1,
           "min": 0,
           "shift": 15,
       },
   ]
},{
   "adr": 38,
   "name": "error1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 16,
   "bit": [
       {
           "name": "errorGenHightFreq",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "errorGenPhaseSeq",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "errorPhaseImbalance",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "errorOverCurrent",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "errorOverPower",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "errorShortCircuit",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "errorMainsPhaseSeq",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "errorMaintenanceOil",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "errorMaintenanceAir",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "errorMaintenanceFuel",
           "mask": 512,
           "max": 1,
           "min": 0,
           "shift": 9,
       },{
           "name": "errorSensorCommon",
           "mask": 1024,
           "max": 1,
           "min": 0,
           "shift": 10,
       },{
           "name": "errorIterruptedStart",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },{
           "name": "errorIterruptedStop",
           "mask": 4096,
           "max": 1,
           "min": 0,
           "shift": 12,
       },{
           "name": "errorUserA",
           "mask": 8192,
           "max": 1,
           "min": 0,
           "shift": 13,
       },{
           "name": "errorUserB",
           "mask": 16384,
           "max": 1,
           "min": 0,
           "shift": 14,
       },{
           "name": "errorUserC",
           "mask": 32768,
           "max": 1,
           "min": 0,
           "shift": 15,
       },
   ]
},{
   "adr": 39,
   "name": "error2",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 1,
   "bit": [
       {
           "name": "errorUserD",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },
   ]
},{
   "adr": 40,
   "name": "warning0",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 16,
   "bit": [
       {
           "name": "warningMainsLowVoltage",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "warningMainsHightVoltage",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "warningMainsLowFreq",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "warningMainsHightFreq",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "warningGenLowVoltage",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },{
           "name": "warningGenHightVoltage",
           "mask": 32,
           "max": 1,
           "min": 0,
           "shift": 5,
       },{
           "name": "warningGenLowFreq",
           "mask": 64,
           "max": 1,
           "min": 0,
           "shift": 6,
       },{
           "name": "warningGenHightFreq",
           "mask": 128,
           "max": 1,
           "min": 0,
           "shift": 7,
       },{
           "name": "warningBatteryLow",
           "mask": 256,
           "max": 1,
           "min": 0,
           "shift": 8,
       },{
           "name": "warningBatteryHight",
           "mask": 512,
           "max": 1,
           "min": 0,
           "shift": 9,
       },{
           "name": "warningOverCurrent",
           "mask": 1024,
           "max": 1,
           "min": 0,
           "shift": 10,
       },{
           "name": "warningChargerFail",
           "mask": 2048,
           "max": 1,
           "min": 0,
           "shift": 11,
       },{
           "name": "warningFuelLowLevel",
           "mask": 4096,
           "max": 1,
           "min": 0,
           "shift": 12,
       },{
           "name": "warningFuelHightLevel",
           "mask": 8192,
           "max": 1,
           "min": 0,
           "shift": 13,
       },{
           "name": "warningTempHight",
           "mask": 16384,
           "max": 1,
           "min": 0,
           "shift": 14,
       },{
           "name": "warningOilLowPressure",
           "mask": 32768,
           "max": 1,
           "min": 0,
           "shift": 15,
       },
   ]
},{
   "adr": 41,
   "name": "warning1",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 3,
   "bit": [
       {
           "name": "warningMaintenanceOil",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "warningMaintenanceAir",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "warningMaintenanceFuel",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },
   ]
},{
   "adr": 42,
   "name": "controll",
   "value": 0,
   "default": 0,
   "scale": 0,
   "min": 0,
   "max": 0,
   "units": "",
   "type": "U",
   "rw": "rw",
   "len": 1,
   "bitMapSize": 5,
   "bit": [
       {
           "name": "controllSwitchMode",
           "mask": 1,
           "max": 1,
           "min": 0,
           "shift": 0,
       },{
           "name": "controllStart",
           "mask": 2,
           "max": 1,
           "min": 0,
           "shift": 1,
       },{
           "name": "controllStop",
           "mask": 4,
           "max": 1,
           "min": 0,
           "shift": 2,
       },{
           "name": "controllResetErrors",
           "mask": 8,
           "max": 1,
           "min": 0,
           "shift": 3,
       },{
           "name": "controllSwitchLoad",
           "mask": 16,
           "max": 1,
           "min": 0,
           "shift": 4,
       },
   ]
},];
module.exports.dataReg = dataReg;